#!/usr/bin/env python3
"""
Repair text that was encoded as UTF-8 twice.

The Cost Tables page carried a medal emoji whose bytes had been run through
UTF-8 encoding a second time. Every language rendered it as a run of stray
characters instead of the icon, because the page was copied between languages
with the corruption already in it.

Doubly-encoded text has a recognisable shape: each byte of the original
character becomes its own Latin-1 character, so re-encoding the string as
Latin-1 and decoding it as UTF-8 again recovers the original.

Run from the repository root:  python3 tools/fix_mojibake.py
"""

from __future__ import annotations

import os
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGETS = ["src/data/tips.yml"]

HEADER = (
    "# Cost tables, generated by tools/extract_tables.py.\n"
    "# The numbers live here once and are shared by every language; the text\n"
    "# is translated through src/i18n/terms/<lang>.yml.\n"
    "#\n"
    "# A cell is written as a plain string when it is an ordinary cell, and as\n"
    "# a mapping only when it needs something extra:\n"
    "#     t   the text\n"
    "#     th  true if it is a header cell\n"
    "#     cls class list, when it differs from the default for its position\n"
    "#     c/r colspan / rowspan\n"
)


def looks_doubly_encoded(s: str) -> bool:
    return any(0x80 <= ord(ch) <= 0xFF for ch in s)


def repair_string(s: str) -> tuple[str, bool]:
    if not looks_doubly_encoded(s):
        return s, False

    # Straightforward case: the whole string round-trips.
    try:
        decoded = s.encode("latin-1").decode("utf-8")
        if not any(ord(ch) < 32 and ch not in "\n\t" for ch in decoded):
            return decoded, True
    except (UnicodeEncodeError, UnicodeDecodeError):
        pass

    # Harder case: a four-byte character lost its final byte. U+0085 is NEL,
    # which Python's \s matches, so whitespace normalisation during extraction
    # silently ate the last byte of every trailing medal emoji. Rebuild from
    # the lead bytes that survived: each 0xF0 begins one four-byte character.
    codes = [ord(ch) for ch in s]
    if codes and all(c in (0xF0, 0x9F, 0x8F, 0x85) for c in codes):
        medals = codes.count(0xF0)
        if medals:
            return "\U0001F3C5" * medals, True

    return s, False


def walk(node, counter: list[int]):
    if isinstance(node, str):
        fixed, changed = repair_string(node)
        if changed:
            counter[0] += 1
        return fixed
    if isinstance(node, list):
        return [walk(x, counter) for x in node]
    if isinstance(node, dict):
        return {walk(k, counter): walk(v, counter) for k, v in node.items()}
    return node


def main() -> int:
    total = 0
    for rel in TARGETS:
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            continue
        with open(path, encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
        counter = [0]
        fixed = walk(data, counter)
        if counter[0]:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(HEADER)
                fh.write(yaml.safe_dump(fixed, allow_unicode=True, sort_keys=False, width=200))
            print(f"{rel}: repaired {counter[0]} string(s)")
            total += counter[0]
        else:
            print(f"{rel}: nothing to repair")
    if total:
        print("\nRun tools/build.py to regenerate the pages.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
